### ISSUE TITLE
normalizeTemplateName doesn't work correctly when there is more than one `\` in the relative path

### ISSUE THREAD

**Issue by gcwilliams** [teambition/gulp-ng-template#1]
Hi,

I've been using your plugin to in-line my templates as part of my release build and it's been working really well. However, some of my templates are more than one directory deep, and the normalize name function does not replace all of the `\` in the relative path.

`"template\carousel\carousel.html" -> "template/carousel\carousel.html"`

this should be 

`"template\carousel\carousel.html" -> "template/carousel/carousel.html"`

the following should fix the issue

```
function normalizeTemplateName(name) {
    return name.replace(/\\/g, '/');
}
```

**Comment by zensh** [comment]
I can't connect to npmjs.org because of GFW, I will publish new version to NPM tomorrow.

> v0.1.2 released
